person = input('Enter your name: ')
print('Hello', person)
age = input('Enter your age: ')
print('Hello', person, '!', 'Your age is:', age, sep=' ')
xString = input("Enter a number: ")
x = int(xString)
yString = input("Enter a second number: ")
y = int(yString)
print('The sum of', x, 'and', y, 'is', x+y, '.', sep=' ')
z = int(input("Enter a third number: "))
print('Substracting', z, 'from', y, 'gives us:', y-z, '.', sep=' ')